### ISSUE TITLE
Default Templates support for Areas

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Simple-Page-Builder#34] opened 2015-08-13 15:41 UTC
Right now I can't setup a default template and configure what parts are in what areas by default, so I'm having to configure on a per-post basis.

https://cloudup.com/c2GNxJ6lCAV+

**Comment by jazzsequence** [comment] 2015-10-03 01:15
duplicate of #41

**Closed as completed by jazzsequence** 2015-10-03 01:15 UTC
Labels: enhancement
